- src/rebar3_ex_doc.erl
Add the `ebin` directories of dependencies to the code path using `ex_doc`'s `--paths` option.  Otherwise, if `foo.erl` references `dep:type/0`, this results in the following warning:
```
warning: documentation references type "dep:type/0" but it is undefined or private
src/foo.erl:37: dep.type/0
```
> Add dependencies to code path

- README.md
- src/rebar3_ex_doc.erl
- test/rebar3_ex_doc_SUITE.erl
We:
1. prevent mixed use of atoms, strings and binaries (prefer Erlang strings everywhere - syntax is the same as Elixir strings),
2. have `main` be readable as a filename, so a reference is easy to understand,
3. keep backward compatibility by only modifying the stuff we "see" in the _new format_.
Closes #20.
Some questions still remain, though.
`README.md` (from `rebar3_ex_doc`) refers `source_url`, for example, but I don't see that (in [mix docs](https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html)) inside `docs`, so it's confusing (is there some kind of modification already done by `mix docs` here)? (I do see `source_url_pattern`, there). **Edit**: refer to the latest commit for changes regarding this.
~We're being explicit in the keys we want to handle, so whatever isn't in the `docs` …
> Tweak expectations for rebar.config

- src/rebar3_ex_doc.erl
Fixes crashes on projects with short forms in their `rebar.config`, e.g. `{edoc_opts, [preprocess]}.`
> gen_chunks: unfold edoc_opts from project rebar.config before merging defaults

- src/rebar3_ex_doc.erl
- test/rebar3_ex_doc_SUITE.erl
This fixes an issue where by order of extra pages got reversed due to a `foldl/2` operation. 
Closes #27
> Switch foldl to foldr to preserve extra pages order

- CHANGELOG.md
- src/rebar3_ex_doc.erl
- edoc opts were erroneously set to include hidden and private module and/or fun docs
by default. This bug was not revealed until a change was put in place in OTP 25.
Closes #17
> Fix default edoc opts

- src/rebar3_ex_doc.erl
The logo option works out-of-the-box so we can skip emitting a warning. In ExDoc, the logo configuration option is a `nil | Path.t()`[^1] and charlists are valid paths[^2], so conversion to a binary is not necessary.
[^1]: https://github.com/elixir-lang/ex_doc/blob/a43392a1c84c4bd67f8e173b34b5d10f476beb5a/lib/ex_doc/config.ex#L65
[^2]: https://github.com/elixir-lang/elixir/blob/v1.14.1/lib/elixir/lib/path.ex#L19, https://github.com/elixir-lang/elixir/blob/v1.14.1/lib/elixir/lib/io.ex#L123
> Prevent warnings when passing the "logo" option

- src/rebar3_ex_doc.erl
ExDoc uses this option to silence autolink warnings (warnings like "X references "init/1" but it is hidden") in [`ExDoc.Autolink.maybe_warn`](https://github.com/elixir-lang/ex_doc/blob/41475624f292897237e6aba3c8f8ecadc6836330/lib/ex_doc/autolink.ex#L123-L131). The skips in this list are checked against binaries so to translate between rebar3_ex_doc and ExDoc, we only need to ensure that each of the skipped elements is a binary.
> Translate 'skip_undefined_reference_warnings_on' ExDoc option

- src/rebar3_ex_doc.erl
Both edoc and ex_doc use the same default output directory (doc/). We can now override the ex_doc default via rebar.config.
> add support for the "output" configuration option

- README.md
- src/rebar3_ex_doc.erl
This adds support for an external config file, for example if you want to share the config with Elixir or as an escape hatch to be able to use a `fun` for `:filter_modules`.
> Allow external config file

- README.md
- src/rebar3_ex_doc.erl
This PR adds the ability to specify whether the docs you're generating for your project is or will be a package on hex. There's still some hex links that remain, but that has to be fixed up in ex_doc itself. 
Resolves #16
> Allow generation of docs outside the context of a package

- README.md
- src/rebar3_ex_doc.erl
Add option to opt of out of prefixing source ref version with `v`.  
Resolves #18
> Provide option to opt of out of prefixing source vsn with v

- src/rebar3_ex_doc.erl
These should be the same type as `ex_doc`'s, right? i.e. "no conversion required" (?)
> Remove warnings from examples

- src/rebar3_ex_doc.erl
When [mermaid][1] support is enabled, also inject the code snippet [suggested in the ExDoc README][2] (into the HTML `<body/>` rather than the `<head/>`).  This resolves rendering issues such as the menu not being displayed properly.  See, for example:
https://eturnal.net/tmp/rendering-broken/
When I access that page (on desktop), the menu items on the left aren't displayed (until I press PAGES/MODULES).  This happens on pages without mermaid diagrams as well.
With this PR applied, things appear to be rendered fine:
https://eturnal.net/tmp/rendering-fixed/
I must admit that I'm not a web dev and am not entirely sure regarding the details here.  However, I figured that following the 'official' ExDoc advice seems fine if it resolves issues.
[1]: https://mermaid.js.org
[2]: …
> Fix rendering issues when mermaid is used

- README.md
- rebar.config
- src/rebar3_ex_doc.erl
List of changes:
- fix typos
- disable warnings on readme on doc references
- remove `$` from shell code block when click and copy
> Minor doc changes

- src/rebar3_ex_doc.app.src
`include_files` was deprecated in rebar3_hex (partially by me 😝), we should be using `include_paths` instead. This commit addresses this problem.
> Use include_paths directive in app.src

- README.md
- src/rebar3_ex_doc.app.src
We publish the README to hex.pm but rely on implicit linking on github which will result in 404 for users trying to hit examples from hexdocs.
Closes #76 
I originally said we'd fix this once the repo is transferred to jelly-beam, but that's a bit silly, a bug exists, it should be fixed. We can just update it as part of the transfer.
> Fix link to example in README.md

- src/rebar3_ex_doc.erl
- test/rebar3_ex_doc_SUITE.erl
Although it seems like an easy problem, it turned out to be pretty nasty. But apart from solving this particular problem, 2 more problems are solved:
1. `ex_doc` seemed to ignore multiple "before_closing_body_tag"s, so in previous solution it wasn't possible to inject custom html while using `with_mermaid` option.
2. Mermaid script element wasn't closed properly so browser ended up merging those 2 script elements effectively ignoring the whole event listener.
Tried my best, but didn't come up with an elegant solution, but it works. Suggestions are very welcome!
Closes #63
> Fix `with_mermaid`

- .github/workflows/up_ex_doc_version.yml
I'm proposing a workflow failure verification mechanism, via [an issue in this repo.](https://github.com/starbelly/rebar3_ex_doc/issues/85), to allow us to understand when the scheduled `up_ex_doc_version` might be failing.
**Note**: inspiration to this came from https://docs.renovatebot.com/, and the way they maintain dependency versioning via a control issue.
If `rebar3 do dialyzer, ct` fails, we reopen (whether it's closed or not) the control issue (#85) and update its title and body, with a link to the failing workflow (after which visual inspect follows). We keep the concurrency of running that workflow to `1` to prevent a further success from closing the issue if it's already open. Hopefully, we'll not have to manage the issue by hand (since the schedule CI workflow should do that …
> Allow for a control issue to let us know when CI's failing

- .github/workflows/ci.yml
- .github/workflows/up_ex_doc_version.yml
- README.md
- src/rebar3_ex_doc.erl
We thus align with other tools doing the same in the ecosystem, e.g. like `rebar3`. Lemme know if you feel this is a drastic change. (I think we discussed it, which is why we find `oldest`, `plus_one`, `plus_two`, `plus_three` in the workflow files, but I can't quite say when - or if we did 😄)
> Move support window to OTP 25-27

- .github/workflows/ci.yml
- .tool-versions
Something's failing with `latest`, in CI, and I wanna make sure we can debug as best we can, so we move to `fail-fast: false`.
> Allow CI to go as far as it can

- release.sh
The current version in the repository will only download the version of OTP being used. At this point, and per changes made in previous endeavors in both ex_doc and rebar3_ex_doc we no longer need to build and ship a version compatible with many versions of OTP. 
The changes in this commit simply adjust to iterate over all supported versions (per ex_doc builds).
> Update release script

- README.md
- src/rebar3_ex_doc.erl
- test/rebar3_ex_doc_SUITE.erl
Ex doc seems to deal differently with assets these days and accepts a map with source -> target entries.
In order to fix that, I added two tests that for checking that assets are created.
One that checks that the legacy form can still be used and one that checks that the new version works.
I have also improved the default testing by not depending on "extras" in all configs.
> Fix assets

- src/rebar3_ex_doc.erl
Some projects may use include files outside `include` directory by specifying them in the `erl_opts` of rebar.config.
For example:
```erlang
{erl_opts, [debug_info, warnings_as_errors, {i, "./_build/default/plugins/gpb/include/"}]}.
```
In order to generate documentation for such projects, I added those includes to the defaults for the edoc provider
> Allow users to put include directives in their erl_opts

- src/rebar3_ex_doc.erl
- test/rebar3_ex_doc_SUITE.erl
Since this commit:
https://github.com/elixir-lang/ex_doc/commit/15f3a593898647800b9b9ba6660696dfa7ff4a0a sending in a map would no longer work, it is a keyword list that is expected for the extra arguments.
That is why the tests fail in the repository for version 0.2.27.
I am a bit unhappy that the code for creating the options is just a copy in both test and production code. The comparison `?assertMatch(Extra, ExpExtra)` is in that sense just a comparison between two different copies of the code and do not relate to the code that `ex_doc` expects.
I did not want to rewrite that part of the code, because it has nothing to do with the actual failure itself.
> ex_doc version v0.38.1 demands KeyWords instead of Maps
